### PR TITLE
We should allow passing empty filters

### PR DESCRIPTION
**Pull request by blabno**
One of our apps really needs this.

### CODE REVIEW

**Comment by mavdi** [comment]
Can you explain the background to this?

**Comment by blabno** [comment]
For dynamic auth, IAM creates filters based on allowed relationships. In case user does not have any items related to their xUser then we should return them empty collection. This was achieved with passing `?filter[id]=` (empty value).

**Comment by blabno** [comment]
Of course I could always not send query with empty filter, but before that:
```
if (_.isEmpty(ownerUserList)) {
    reply({data: []})
    return;
}
```
But that would require updating those places in code every time we modify additional metadata we send with such JSONAPI response.

**Comment by blabno** [comment]
We've decided, not to merge this for now.

**Pull request closed without merging**
