### PR TITLE
added ability to define Joi.object() in schemas

### PR DESCRIPTION
**Pull request by ShurakaiSoft**
Allow Joi.object() types in hapi-harvester schemas.

### CODE REVIEW

**Comment by ShurakaiSoft** [comment]
This PR uses [github flow](http://scottchacon.com/2011/08/31/github-flow.html).  So it branched from master and is being requested to be merged back into master. See issue #48

**Comment by kristofsajdak** [comment]
Not sure whether this change covers the full load of adding subdocuments support into hapi-harvester. 

This seems to add Joi.object() support, but does not handle the inner document, so it results in a kind of allow-all definition. What does the json-api spec has to say about this is another question which comes to mind.

**Comment by mavdi** [comment]
Closing this PR, since I'm not sure we need nested objects or that JSON API supports it.

**Comment by mavdi** [comment]
Well, no longer have access. @hendrikbeneke can you close this please?

**Comment by dclucas** [comment]
The spec explicitly allows for nested objects and arrays -- I don't think this, or the original bug, should be closed:

> Complex data structures involving JSON objects and arrays are allowed as attribute values. However, any object that constitutes or is contained in an attribute MUST NOT contain a relationships or links member, as those members are reserved by this specification for future use.

**Pull request closed without merging**
