### PR TITLE
Fixes dependency break on recent npm versions.

### PR DESCRIPTION
**Pull request by dclucas**
This change adds an explicit dependency to the mongodb package and removes the dependency from the internal mongoose reference (in mongoose/node_modules/mongodb)

### CODE REVIEW

**Comment by kristofsajdak** [comment]
Hey Diogo, 

Thanks for submitting the PR, I'll close off [70](https://github.com/agco/hapi-harvester/pull/70/files) when this gets merged.

Was there a reason you want to apply this to the master branch as a hotfix ? Can we not apply it to develop and release from there.

Regards,

K

**Comment by dclucas** [comment]
I thought we were using git-flow, which would make this a hotfix. And travis is configured to deploy from master, so the merge would be more straightforward. After the merge to master, we can then merge into develop as well (I can take the action, BTW, as this should not require yet another PR).

**Comment by dclucas** [comment]
It's a good thing you asked -- this made me remember to bump the version :)

**Comment by kristofsajdak** [comment]
Hey Diogo,

My understanding was that a hotfix is applicable when you want to patch a production release. Makes sense to me if you want to release a 0.4.1 without the additional new code in the current develop branch.
 
That said, don't mind merging the PR as-is if you want to move forward like this. The important thing is that we backport the fix to develop.

**Pull request merged**
